In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
casual_df=pd.read_csv('Casualties0514.csv')
accident_df=pd.read_csv('Accidents0514.csv')
vehicle_df=pd.read_csv('Vehicles0514.csv')

C:\Users\tamil\AppData\Local\Temp\ipykernel_238112\3558190798.py:2: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  accident_df=pd.read_csv('Accidents0514.csv')


In [4]:
first_df=pd.merge(casual_df,accident_df,on='Accident_Index')

In [5]:
df=pd.merge(first_df,vehicle_df,on='Accident_Index')

In [6]:
df.drop('LSOA_of_Accident_Location',axis=1,inplace=True)


In [7]:
df.dropna(subset=['Time'],axis=0,inplace=True)
df

Accident_Index  Vehicle_Reference_x  Casualty_Reference  \
0        200501BS00001                    1                   1   
1        200501BS00002                    1                   1   
2        200501BS00003                    2                   1   
3        200501BS00003                    2                   1   
4        200501BS00004                    1                   1   
...                ...                  ...                 ...   
4287588  2014984138414                    2                   2   
4287589  2014984139614                    1                   2   
4287590  2014984139614                    1                   2   
4287591  2014984139614                    2                   1   
4287592  2014984139614                    2                   1   

         Casualty_Class  Sex_of_Casualty  Age_of_Casualty  \
0                     3                1               37   
1                     2                1               37   
2                     1                1               62   
3                     1                1               62   
4                     3                1               30   
...                 ...              ...              ...   
4287588               1                1               44   
4287589               2                1               61   
4287590               2                1               61   
4287591               1                1               79   
4287592               1                1               79   

         Age_Band_of_Casualty  Casualty_Severity  Pedestrian_Location  \
0                           7                  2                    1   
1                           7                  3                    0   
2                           9                  3                    0   
3                           9                  3                    0   
4                           6                  3                    5   
...                       ...                ...                  ...   
4287588                     7                  2                    0   
4287589                     9                  3                    0   
4287590                     9                  3                    0   
4287591                    11                  3                    0   
4287592                    11                  3                    0   

         Pedestrian_Movement  ...  Was_Vehicle_Left_Hand_Drive?  \
0                          1  ...                             1   
1                          0  ...                             1   
2                          0  ...                             1   
3                          0  ...                             1   
4                          2  ...                             1   
...                      ...  ...                           ...   
4287588                    0  ...                             1   
4287589                    0  ...                             1   
4287590                    0  ...                             1   
4287591                    0  ...                             1   
4287592                    0  ...                             1   

         Journey_Purpose_of_Driver  Sex_of_Driver  Age_of_Driver  \
0                               15              2             74   
1                                1              1             42   
2                                1              1             35   
3                               15              1             62   
4                               15              2             49   
...                            ...            ...            ...   
4287588                          6              1             73   
4287589                          1              1             40   
4287590                          6              1             79   
4287591                          1              1             40   
4287592                          6      

In [8]:
df.isnull().values.any()

True

In [9]:
df.dropna(inplace=True)


In [10]:
df.isnull().values.any()
df.columns

Index(['Accident_Index', 'Vehicle_Reference_x', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type', 'Location_Easting_OSGR',
       'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force',
       'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties',
       'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)',
       'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number',
       'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control',
       '2nd_Road_Class', '2nd_Road_Number',
       'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Condi

In [11]:
q3_df=pd.DataFrame(data=df,columns=['Longitude','Latitude','1st_Road_Class','2nd_Road_Class','Weather_Conditions'])

In [12]:
q3_df

Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [13]:
X=q3_df.drop('Weather_Conditions',axis=1)
y=q3_df['Weather_Conditions']

q3_df['Weather_Conditions'].unique()

array([ 2,  1,  9,  3,  8,  4,  5,  7,  6, -1], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test= train_test_split(X,y)
X_train.head(20)


Longitude   Latitude  1st_Road_Class  2nd_Road_Class
215387   -2.154835  52.470724               3               3
2430565  -0.216465  51.357560               4               3
451895   -2.111559  52.005244               5              -1
354363   -1.109349  51.699460               3              -1
3192460   0.051055  51.551836               3               6
72339    -2.694485  53.757143               6               6
2988282  -0.422650  52.943379               3               6
391962   -0.809952  51.196035               6               4
3946738  -0.198520  51.580304               3               6
3133110  -2.438556  50.644983               3               6
755874   -2.689944  52.760992               3               6
3358261  -1.395940  53.081760               4               6
1956431  -0.126011  51.500842               3               3
1258793  -1.523536  52.910102               6               4
2127486  -2.015314  52.575559               3              -1
1761369  -0.208732  52.340553               3              -1
4087313  -1.428991  52.230949               4              -1
2291105   0.138286  50.840064               3              -1
3228017  -0.202562  51.360495               3               6
2246956  -1.159069  51.460196               1              -1

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree= DecisionTreeClassifier()

In [18]:
dtree.fit(X_train.values,y_train.values)

DecisionTreeClassifier()

In [19]:
predictions= dtree.predict(X_test.values)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test.values,predictions))

              precision    recall  f1-score   support

          -1       0.72      0.80      0.76       104
           1       0.93      0.95      0.94    852903
           2       0.77      0.72      0.74    131207
           3       0.74      0.69      0.72      7406
           4       0.74      0.68      0.71     13678
           5       0.75      0.69      0.72     15384
           6       0.79      0.74      0.77      1436
           7       0.82      0.77      0.79      7792
           8       0.74      0.67      0.70     23531
           9       0.72      0.65      0.68     18328

    accuracy                           0.90   1071769
   macro avg       0.77      0.74      0.75   1071769
weighted avg       0.90      0.90      0.90   1071769



In [22]:
print(confusion_matrix(y_test.values,predictions))
q3_df

[[    83     17      2      0      1      0      0      0      0      1]
 [    26 812616  24383   1384   2500   2679    213   1029   4308   3765]
 [     4  34397  94209    221    415    552     36    167    691    515]
 [     1   1846    274   5139     20     25      4     16     40     41]
 [     1   3670    456     44   9312     47      7     21     71     49]
 [     0   3822    609     36     76  10636      4     34     84     83]
 [     0    273     59      2      8     14   1065      2      8      5]
 [     0   1442    200     18     25     32      3   6013     38     21]
 [     0   6528    888     71    112     98      7     44  15664    119]
 [     0   5436    648     37     55     84      5     22    130  11911]]


Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [23]:
import pickle
pickle.dump(dtree, open("weather.pkl", "wb"))